const PRODUCTS=[
{id:1,name:'Compact Wireless Label Printer',cat:'Electronics',price:24.99,old:34.99,rating:4.8,reviews:1241,img:'https://images.unsplash.com/photo-1586769852044-692d6e3703f0?auto=format&fit=crop&w=900&q=80',tag:'Best seller',desc:'Fast Bluetooth label printer with simple mobile setup, crisp printing, and no ink required.'},
{id:2,name:'Reusable Silicone Food Storage Set',cat:'Home',price:12.49,old:18.99,rating:4.7,reviews:889,img:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=80',tag:'Rollback',desc:'Flexible reusable food storage containers designed for easy organization and everyday use.'},
{id:3,name:'Pet Grooming Deshedding Tool',cat:'Pets',price:9.98,old:15.99,rating:4.9,reviews:2154,img:'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80',tag:'Top rated',desc:'Comfort-grip grooming tool that helps remove loose fur while staying gentle on pets.'},
{id:4,name:'Magnetic Phone Car Mount',cat:'Auto',price:8.99,old:13.49,rating:4.6,reviews:632,img:'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=80',tag:'Value pick',desc:'Strong magnetic mount with a compact dashboard design and adjustable viewing angle.'},
{id:5,name:'USB-C Multiport Travel Hub',cat:'Electronics',price:19.95,old:29.95,rating:4.8,reviews:1788,img:'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80',tag:'Popular',desc:'Portable USB-C hub with multiple ports for work, travel, and everyday connectivity.'},
{id:6,name:'Microfiber Cleaning Cloths 24-Pack',cat:'Home',price:11.99,old:16.99,rating:4.7,reviews:908,img:'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=900&q=80',tag:'Everyday low price',desc:'Soft reusable microfiber cloths for kitchens, cars, screens, and general cleaning.'},
{id:7,name:'Comfort Memory Foam Insoles',cat:'Health',price:14.75,old:21.99,rating:4.5,reviews:544,img:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',tag:'Customer favorite',desc:'Cushioned insoles made for comfortable daily walking and standing support.'},
{id:8,name:'Compact Digital Kitchen Scale',cat:'Kitchen',price:10.49,old:14.99,rating:4.8,reviews:1145,img:'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80',tag:'Top rated',desc:'Slim digital scale with a clear display and accurate measurements for everyday cooking.'},
{id:9,name:'Portable Mini Desk Fan',cat:'Local US',price:16.99,old:22.99,rating:4.6,reviews:401,img:'https://images.unsplash.com/photo-1598300056393-4aac492f4344?auto=format&fit=crop&w=900&q=80',tag:'Fast shipping',desc:'Quiet rechargeable desk fan with adjustable airflow and a compact travel-ready design.'},
{id:10,name:'Adjustable Laptop Stand',cat:'Electronics',price:21.49,old:31.99,rating:4.9,reviews:1987,img:'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=900&q=80',tag:'Best seller',desc:'Stable adjustable stand that raises laptops for more comfortable work and viewing.'},
{id:11,name:'Heavy-Duty Closet Organizer',cat:'Home',price:17.95,old:25.99,rating:4.5,reviews:388,img:'https://images.unsplash.com/photo-1616486338815-3e9c88d8d98f?auto=format&fit=crop&w=900&q=80',tag:'Smart buy',desc:'Space-saving organizer with reinforced shelves for closets, bedrooms, and storage areas.'},
{id:12,name:'Rechargeable Book Light',cat:'Local US',price:7.99,old:12.99,rating:4.7,reviews:759,img:'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=900&q=80',tag:'Under $10',desc:'Compact clip-on reading light with adjustable brightness and USB charging.'}
];
const CATEGORIES=[['All','☰'],['Electronics','🎧'],['Home','🏠'],['Kitchen','🍳'],['Pets','🐾'],['Health','🧴'],['Local US','⚡']];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const money=n=>'$'+Number(n||0).toFixed(2);
let cart=read('yooop-cart',{}), user=read('yooop-user',null), orders=read('yooop-orders',[]), selected='All', sort='featured', query='';
function cartItems(){return Object.entries(cart).map(([id,qty])=>({p:PRODUCTS.find(x=>x.id===+id),qty:+qty})).filter(x=>x.p)}
function cartCount(){return cartItems().reduce((a,x)=>a+x.qty,0)}
function subtotal(){return cartItems().reduce((a,x)=>a+x.p.price*x.qty,0)}
function shipping(){return subtotal()>=35||subtotal()===0?0:5.99}
function saveCart(){write('yooop-cart',cart);updateBadges()}
function updateBadges(){$$('[data-cart-count],#cartCount').forEach(x=>x.textContent=cartCount());$$('[data-user-name]').forEach(x=>x.textContent=user?.first||user?.name||'Account')}
function toast(t='Done'){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';document.body.append(el)}el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1500)}
function addToCart(id,qty=1){cart[id]=(cart[id]||0)+qty;saveCart();toast('Added to cart')}
function changeQty(id,d){cart[id]=(cart[id]||0)+d;if(cart[id]<=0)delete cart[id];saveCart();renderCartPage()}
function removeFromCart(id){delete cart[id];saveCart();renderCartPage()}
function productCard(p){return `<article class="product-card"><a class="product-link" href="product.html?id=${p.id}"><img class="product-img" src="${p.img}" alt="${p.name}"><div class="product-body"><span class="badge">${p.tag}</span><div class="product-name">${p.name}</div><div class="rating">★★★★★ <span class="muted">${p.rating} (${p.reviews})</span></div><div><span class="price">${money(p.price)}</span><span class="was">${money(p.old)}</span></div><div class="delivery">Free pickup available</div></div></a><button class="add-circle" aria-label="Add ${p.name}" onclick="addToCart(${p.id})">+</button></article>`}
function getFiltered(){let list=PRODUCTS.filter(p=>(selected==='All'||p.cat===selected)&&(!query||`${p.name} ${p.cat}`.toLowerCase().includes(query)));if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);return list}
function renderHome(){const cats=$('#categories'),grid=$('#productGrid');if(!cats||!grid)return;cats.innerHTML=CATEGORIES.map(([n,i])=>`<button class="category-card ${selected===n?'active':''}" onclick="setCategory('${n}')"><span class="category-icon">${i}</span><b>${n}</b></button>`).join('');const list=getFiltered();grid.innerHTML=list.map(productCard).join('')||'<div class="empty">No products found.</div>';const rt=$('#resultsText');if(rt)rt.textContent=`${list.length} products`}
function setCategory(c){selected=c;renderHome();$('#products')?.scrollIntoView({behavior:'smooth'})}
function setSort(s,el){sort=s;$$('.chip,.filter').forEach(x=>x.classList.remove('active'));el?.classList.add('active');renderHome()}
function applySearch(){query=($('#searchInput')?.value||'').trim().toLowerCase();renderHome();$('#products')?.scrollIntoView({behavior:'smooth'})}
function renderProduct(){const el=$('#productDetail');if(!el)return;const id=+(new URLSearchParams(location.search).get('id')||1),p=PRODUCTS.find(x=>x.id===id)||PRODUCTS[0];document.title=`${p.name} — YOOOP`;el.innerHTML=`<div class="product-detail"><div><img class="detail-image" src="${p.img}" alt="${p.name}"></div><div class="detail-info"><span class="badge">${p.tag}</span><h1>${p.name}</h1><div class="rating">★★★★★ <span class="muted">${p.rating} · ${p.reviews} reviews</span></div><div class="detail-price">${money(p.price)} <span class="was">${money(p.old)}</span></div><p class="muted">${p.desc}</p><ul class="detail-list"><li>30-day easy returns</li><li>Buyer protection included</li><li>Ships from a verified fulfillment partner</li><li>Secure checkout</li></ul><div class="purchase-box"><b>Delivery</b><p>Estimated in 5–10 business days</p><div class="qty-row"><span>Quantity</span><button onclick="detailQty(-1)">−</button><b id="detailQty">1</b><button onclick="detailQty(1)">+</button></div><button class="btn btn-blue" onclick="addDetail(${p.id})">Add to cart</button> <button class="btn btn-yellow" onclick="buyNow(${p.id})">Buy now</button></div></div></div><section class="section"><div class="section-head"><h2>You may also like</h2></div><div class="product-grid">${PRODUCTS.filter(x=>x.id!==p.id).slice(0,5).map(productCard).join('')}</div></section>`}
let dq=1;function detailQty(d){dq=Math.max(1,dq+d);const e=$('#detailQty');if(e)e.textContent=dq}function addDetail(id){addToCart(id,dq)}function buyNow(id){addToCart(id,dq);location.href='checkout.html'}
function renderCartPage(){const el=$('#cartPage');if(!el)return;const items=cartItems();if(!items.length){el.innerHTML=`<div class="panel empty"><h2>Your cart is empty</h2><p>Start shopping to add items.</p><a class="btn btn-blue" href="index.html">Continue shopping</a></div>`;return}el.innerHTML=`<div class="page-title"><h1>Cart</h1><p class="muted">${cartCount()} item${cartCount()===1?'':'s'}</p></div><div class="two-col"><section class="panel">${items.map(({p,qty})=>`<div class="cart-row"><img src="${p.img}" alt="${p.name}"><div><a href="product.html?id=${p.id}"><b>${p.name}</b></a><div class="muted">${p.cat}</div><div class="delivery">In stock</div><div class="qty-row"><button onclick="changeQty(${p.id},-1)">−</button><b>${qty}</b><button onclick="changeQty(${p.id},1)">+</button><button class="btn btn-outline" onclick="removeFromCart(${p.id})">Remove</button></div></div><strong>${money(p.price*qty)}</strong></div>`).join('')}</section><aside class="panel"><h2>Order summary</h2><div class="summary-row"><span>Subtotal</span><b>${money(subtotal())}</b></div><div class="summary-row"><span>Shipping</span><b>${shipping()?money(shipping()):'Free'}</b></div><div class="summary-row summary-total"><span>Estimated total</span><b>${money(subtotal()+shipping())}</b></div><a class="btn btn-blue" style="width:100%" href="checkout.html">Continue to checkout</a><p class="muted" style="font-size:12px">Taxes are calculated at checkout.</p></aside></div>`}
function renderCheckout(){const el=$('#checkoutPage');if(!el)return;const items=cartItems();if(!items.length){el.innerHTML='<div class="panel empty"><h2>No items to check out</h2><a class="btn btn-blue" href="index.html">Shop now</a></div>';return}const u=user||{};el.innerHTML=`<div class="page-title"><h1>Checkout</h1><p class="muted">Secure demo checkout</p></div><form id="checkoutForm" onsubmit="placeOrder(event)" class="two-col"><section class="panel"><h2>Delivery address</h2><div class="form-grid"><div class="field"><label>First name</label><input required name="first" value="${u.first||''}"></div><div class="field"><label>Last name</label><input required name="last" value="${u.last||''}"></div><div class="field full"><label>Email</label><input required type="email" name="email" value="${u.email||''}"></div><div class="field full"><label>Street address</label><input required name="address" value="${u.address||''}"></div><div class="field"><label>City</label><input required name="city" value="${u.city||''}"></div><div class="field"><label>State</label><input required name="state" value="${u.state||''}"></div><div class="field"><label>ZIP code</label><input required name="zip" value="${u.zip||''}"></div><div class="field"><label>Phone</label><input required name="phone" value="${u.phone||''}"></div></div><h2>Payment</h2><div class="notice">Demo only — no card will be charged.</div><div class="form-grid" style="margin-top:12px"><div class="field full"><label>Card number</label><input required inputmode="numeric" placeholder="4242 4242 4242 4242"></div><div class="field"><label>Expiration</label><input required placeholder="MM/YY"></div><div class="field"><label>Security code</label><input required placeholder="CVV"></div></div></section><aside class="panel"><h2>Order summary</h2>${items.map(({p,qty})=>`<div class="summary-row"><span>${qty} × ${p.name}</span><b>${money(p.price*qty)}</b></div>`).join('')}<div class="summary-row"><span>Shipping</span><b>${shipping()?money(shipping()):'Free'}</b></div><div class="summary-row summary-total"><span>Total</span><b>${money(subtotal()+shipping())}</b></div><button class="btn btn-blue" style="width:100%">Place demo order</button></aside></form>`}
function placeOrder(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));user={...(user||{}),...f};write('yooop-user',user);const order={id:'YOOOP-'+Math.floor(10000+Math.random()*89999),date:new Date().toLocaleDateString(),total:subtotal()+shipping(),status:'Processing',items:cartItems(),address:`${f.address}, ${f.city}, ${f.state} ${f.zip}`,steps:[['Order placed',true],['Payment confirmed',true],['Preparing shipment',false],['Shipped',false],['Delivered',false]]};orders.unshift(order);write('yooop-orders',orders);cart={};saveCart();location.href=`orders.html?placed=${order.id}`}
function seedOrders(){if(orders.length)return;orders=[{id:'YOOOP-10428',date:'7/8/2026',total:44.94,status:'In transit',items:[{p:PRODUCTS[0],qty:1},{p:PRODUCTS[5],qty:1}],address:'Brooklyn, NY',steps:[['Order placed',true],['Payment confirmed',true],['Shipped from fulfillment center',true],['In transit to local carrier',true],['Out for delivery',false],['Delivered',false]]}];write('yooop-orders',orders)}
function renderOrders(){const el=$('#ordersPage');if(!el)return;seedOrders();const placed=new URLSearchParams(location.search).get('placed');el.innerHTML=`<div class="page-title"><h1>Your orders</h1><p class="muted">View order details, delivery progress, returns, and support.</p></div>${placed?`<div class="notice" style="margin-bottom:15px">Order ${placed} was placed successfully.</div>`:''}${orders.map(o=>`<article class="order-card"><div class="order-head"><div><small>ORDER PLACED</small><br><b>${o.date}</b></div><div><small>TOTAL</small><br><b>${money(o.total)}</b></div><div><small>ORDER #</small><br><b>${o.id}</b></div></div><div class="order-body"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:15px"><div><span class="status-pill">${o.status}</span><h2 style="margin:9px 0 0">${o.status==='Delivered'?'Delivered':'Arriving soon'}</h2></div><a class="btn btn-outline" href="tracking.html?id=${o.id}">Track package</a></div>${o.items.map(({p,qty})=>`<div class="order-product"><img src="${p.img}"><div><b>${p.name}</b><div class="muted">Qty ${qty}</div></div><div class="order-actions"><a class="btn btn-outline" href="product.html?id=${p.id}">Buy again</a></div></div>`).join('')}</div></article>`).join('')}`}
function renderTracking(){const el=$('#trackingPanel');if(!el)return;seedOrders();const id=new URLSearchParams(location.search).get('id'),o=orders.find(x=>x.id===id)||orders[0];el.innerHTML=`<div class="page-title"><h1>Track package</h1><p class="muted">Order ${o.id}</p></div><div class="two-col"><section class="panel"><span class="status-pill">${o.status}</span><h2>Estimated delivery: 2–4 days</h2><p class="muted">Delivering to ${o.address}</p><div class="timeline">${o.steps.map(([t,d],i)=>`<div class="timeline-step ${d?'done':''}"><b>${t}</b><div class="muted">${d?(i===0?o.date:'Completed'):'Pending'}</div></div>`).join('')}</div></section><aside class="panel"><h2>Shipment</h2>${o.items.map(({p,qty})=>`<div class="order-product"><img src="${p.img}"><div><b>${p.name}</b><div class="muted">Qty ${qty}</div></div></div>`).join('')}<a class="btn btn-outline" style="width:100%;margin-top:15px" href="support.html">Get delivery help</a></aside></div>`}
function renderAccount(){const el=$('#accountPage');if(!el)return;const u=user||{};el.innerHTML=`<div class="page-title"><h1>${u.first?`Hi, ${u.first}`:'Your account'}</h1><p class="muted">Manage orders, profile, messages, and support.</p></div><div class="account-grid"><a class="account-tile" href="orders.html"><span class="account-icon">📦</span><h3>Your orders</h3><p class="muted">Track, return, or buy again</p></a><a class="account-tile" href="messages.html"><span class="account-icon">💬</span><h3>Messages</h3><p class="muted">Support and order conversations</p></a><a class="account-tile" href="support.html"><span class="account-icon">🎧</span><h3>Customer service</h3><p class="muted">Get help with any issue</p></a><a class="account-tile" href="#profile"><span class="account-icon">👤</span><h3>Profile</h3><p class="muted">Name, email, and phone</p></a><a class="account-tile" href="#profile"><span class="account-icon">📍</span><h3>Addresses</h3><p class="muted">Delivery locations</p></a><a class="account-tile" href="login.html"><span class="account-icon">🔒</span><h3>Login & security</h3><p class="muted">Sign in or update access</p></a></div><section class="panel section" id="profile"><div class="section-head"><div><h2>Profile details</h2><p class="muted">Saved on this device for the demo.</p></div></div><form id="accountForm" onsubmit="saveProfile(event)"><div class="form-grid"><div class="field"><label>First name</label><input name="first" value="${u.first||''}"></div><div class="field"><label>Last name</label><input name="last" value="${u.last||''}"></div><div class="field full"><label>Email</label><input type="email" name="email" value="${u.email||''}"></div><div class="field full"><label>Phone</label><input name="phone" value="${u.phone||''}"></div><div class="field full"><label>Street address</label><input name="address" value="${u.address||''}"></div><div class="field"><label>City</label><input name="city" value="${u.city||''}"></div><div class="field"><label>State</label><input name="state" value="${u.state||''}"></div><div class="field"><label>ZIP</label><input name="zip" value="${u.zip||''}"></div></div><button class="btn btn-blue" style="margin-top:15px">Save changes</button></form></section>`}
function saveProfile(e){e.preventDefault();user={...(user||{}),...Object.fromEntries(new FormData(e.target))};write('yooop-user',user);updateBadges();toast('Profile saved')}
function login(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));user={...(user||{}),email:f.email,first:f.name||f.email.split('@')[0]};write('yooop-user',user);location.href='account.html'}
function register(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));user={first:f.first,last:f.last,email:f.email};write('yooop-user',user);location.href='account.html'}
function logout(){localStorage.removeItem('yooop-user');user=null;location.href='login.html'}
function renderMessages(){const body=$('#threadBody');if(!body)return;let msgs=read('yooop-messages',[{who:'agent',text:'Hi! Welcome to YOOOP Support. How can we help today?'},{who:'agent',text:'You can ask about an order, return, refund, delivery, or account issue.'}]);body.innerHTML=msgs.map(m=>`<div class="msg ${m.who}">${m.text}</div>`).join('');body.scrollTop=body.scrollHeight}
function sendMessage(e){e.preventDefault();const inp=$('#messageText'),text=inp.value.trim();if(!text)return;let msgs=read('yooop-messages',[]);msgs.push({who:'user',text});write('yooop-messages',msgs);inp.value='';renderMessages();setTimeout(()=>{msgs=read('yooop-messages',[]);msgs.push({who:'agent',text:'Thanks — we received your message. A support specialist will review it. For immediate help, open AI Support.'});write('yooop-messages',msgs);renderMessages()},600)}
function createTicket(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),id='CASE-'+Math.floor(100000+Math.random()*899999),tickets=read('yooop-tickets',[]);tickets.unshift({...f,id,date:new Date().toLocaleString(),status:'Open'});write('yooop-tickets',tickets);e.target.reset();const r=$('#ticketResult');if(r)r.innerHTML=`<div class="notice" style="margin-top:12px">Support case <b>${id}</b> was created.</div>`}
function clearChat(){write('yooop-ai-chat',[]);renderAI()}
function aiReply(text){const t=text.toLowerCase();if(t.includes('track')||t.includes('where')&&t.includes('order'))return `Open <a href="orders.html">Your Orders</a> and choose “Track package” for the latest timeline.`;if(t.includes('return'))return `You can start with <a href="orders.html">Your Orders</a>. Select the item and contact support for a return authorization.`;if(t.includes('refund'))return 'Refunds are usually sent to the original payment method after the return is received and inspected.';if(t.includes('cancel'))return 'Orders can only be cancelled before fulfillment begins. Open Your Orders or create a support case immediately.';if(t.includes('login')||t.includes('password')||t.includes('account'))return `Open <a href="login.html">Login & Security</a> or <a href="account.html">Your Account</a> to update your information.`;if(t.includes('human')||t.includes('agent'))return `I can create a support case for a human specialist. Open <a href="support.html">Customer Service</a> and submit the issue.`;if(t.includes('damaged')||t.includes('missing'))return `I’m sorry about that. Please open <a href="support.html">Customer Service</a>, choose “Order problem,” and include your order number.`;return 'I can help with orders, tracking, returns, refunds, cancellations, delivery problems, account access, or product questions. Tell me what happened and include an order number when available.'}
function renderAI(){const body=$('#aiBody');if(!body)return;let chat=read('yooop-ai-chat',[]);if(!chat.length)chat=[{who:'agent',text:'Hi! I’m the YOOOP AI Assistant. How can I help with your shopping or order today?'}];body.innerHTML=chat.map(m=>`<div class="msg ${m.who}">${m.text}</div>`).join('');body.scrollTop=body.scrollHeight}
function sendAI(e){e.preventDefault();const inp=$('#aiInput'),text=inp.value.trim();if(!text)return;let chat=read('yooop-ai-chat',[]);chat.push({who:'user',text});write('yooop-ai-chat',chat);inp.value='';renderAI();const body=$('#aiBody');const typing=document.createElement('div');typing.className='typing';typing.innerHTML='<i></i><i></i><i></i>';body.append(typing);body.scrollTop=body.scrollHeight;setTimeout(()=>{chat=read('yooop-ai-chat',[]);chat.push({who:'agent',text:aiReply(text)});write('yooop-ai-chat',chat);renderAI()},650)}
function askAI(t){const inp=$('#aiInput');if(inp){inp.value=t;$('#aiForm')?.requestSubmit()}}
function init(){updateBadges();renderHome();renderProduct();renderCartPage();renderCheckout();renderOrders();renderTracking();renderAccount();renderMessages();renderAI();$('#searchInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')applySearch()})}
document.addEventListener('DOMContentLoaded',init);