const products=[
{id:1,name:'Compact Wireless Label Printer',cat:'Electronics',price:24.99,old:34.99,rating:4.8,img:'https://images.unsplash.com/photo-1586769852044-692d6e3703f0?auto=format&fit=crop&w=900&q=80',tag:'Top pick',desc:'A compact Bluetooth label printer for shipping labels, organization, and small-business use.'},
{id:2,name:'Reusable Silicone Food Storage Set',cat:'Home',price:12.49,old:18.99,rating:4.7,img:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=80',tag:'Best value',desc:'Reusable storage containers designed to save space and reduce disposable plastic use.'},
{id:3,name:'Pet Grooming Deshedding Tool',cat:'Pets',price:9.98,old:15.99,rating:4.9,img:'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80',tag:'Loved',desc:'A comfortable grooming tool for removing loose pet hair and maintaining a healthy coat.'},
{id:4,name:'Magnetic Phone Car Mount',cat:'Auto',price:8.99,old:13.49,rating:4.6,img:'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=80',tag:'Fast ship',desc:'A secure magnetic phone mount with adjustable viewing angles for safer navigation.'},
{id:5,name:'USB-C Multiport Travel Hub',cat:'Electronics',price:19.95,old:29.95,rating:4.8,img:'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80',tag:'Trending',desc:'Expand one USB-C port into multiple useful connections for travel, work, and school.'},
{id:6,name:'Microfiber Cleaning Cloths 24-Pack',cat:'Home',price:11.99,old:16.99,rating:4.7,img:'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=900&q=80',tag:'Everyday',desc:'Soft reusable microfiber cloths for kitchens, cars, glass, electronics, and everyday cleanup.'},
{id:7,name:'Comfort Memory Foam Insoles',cat:'Health',price:14.75,old:21.99,rating:4.5,img:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',tag:'Popular',desc:'Cushioned memory-foam insoles designed for everyday comfort and support.'},
{id:8,name:'Compact Digital Kitchen Scale',cat:'Kitchen',price:10.49,old:14.99,rating:4.8,img:'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80',tag:'Top rated',desc:'A precise digital scale for cooking, baking, meal prep, and portion control.'},
{id:9,name:'Portable Mini Desk Fan',cat:'Local US',price:16.99,old:22.99,rating:4.6,img:'https://images.unsplash.com/photo-1598300056393-4aac492f4344?auto=format&fit=crop&w=900&q=80',tag:'Local US',desc:'A quiet portable fan with adjustable airflow for desks, bedrooms, and travel.'},
{id:10,name:'Adjustable Laptop Stand',cat:'Electronics',price:21.49,old:31.99,rating:4.9,img:'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=900&q=80',tag:'Best seller',desc:'An adjustable stand that raises your laptop for a cleaner and more comfortable workspace.'},
{id:11,name:'Heavy-Duty Closet Organizer',cat:'Home',price:17.95,old:25.99,rating:4.5,img:'https://images.unsplash.com/photo-1616486338815-3e9c88d8d98f?auto=format&fit=crop&w=900&q=80',tag:'Smart find',desc:'A durable organizer for clothing, shoes, accessories, and extra household storage.'},
{id:12,name:'Rechargeable Book Light',cat:'Local US',price:7.99,old:12.99,rating:4.7,img:'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=900&q=80',tag:'Under $10',desc:'A compact rechargeable reading light with adjustable brightness and a flexible neck.'}
];
const categories=[['All','✨'],['Electronics','🎧'],['Home','🏠'],['Kitchen','🍳'],['Pets','🐾'],['Local US','🇺🇸']];
let selected='All',sort='featured',query='',cart=JSON.parse(localStorage.getItem('yooop-cart')||'{}');
const money=n=>'$'+Number(n).toFixed(2);
const cartItems=()=>Object.entries(cart).map(([id,qty])=>({p:products.find(x=>x.id===Number(id)),qty})).filter(x=>x.p);
function saveCart(){localStorage.setItem('yooop-cart',JSON.stringify(cart));updateCartBadges();renderCartPage();}
function updateCartBadges(){const count=cartItems().reduce((a,x)=>a+x.qty,0);document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=count);const legacy=document.getElementById('cartCount');if(legacy)legacy.textContent=count;}
function addToCart(id,go=false){cart[id]=(cart[id]||0)+1;saveCart();showToast();if(go)setTimeout(()=>location.href='cart.html',250);}
function changeQty(id,delta){cart[id]=(cart[id]||0)+delta;if(cart[id]<=0)delete cart[id];saveCart();}
function removeFromCart(id){delete cart[id];saveCart();}
function showToast(){const t=document.getElementById('toast');if(!t)return;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1200);}
function renderCategories(){const el=document.getElementById('categories');if(!el)return;el.innerHTML=categories.map(([name,icon])=>`<button class="category ${selected===name?'active':''}" onclick="setCategory('${name}')"><span>${icon}</span><strong>${name}</strong></button>`).join('');}
function getProducts(){let list=products.filter(p=>(selected==='All'||p.cat===selected)&&(!query||p.name.toLowerCase().includes(query)||p.cat.toLowerCase().includes(query)));if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);return list;}
function renderProducts(){const grid=document.getElementById('productGrid');if(!grid)return;const list=getProducts();const results=document.getElementById('resultsText');if(results)results.textContent=`${list.length} products`;grid.innerHTML=list.map(p=>`<article class="product"><a class="product-link" href="product.html?id=${p.id}"><div class="product-image"><img src="${p.img}" alt="${p.name}"></div><div class="product-info"><span class="tag">${p.tag}</span><div class="product-title">${p.name}</div><div class="rating">★★★★★ <span class="subtle">${p.rating}</span></div></div></a><div class="product-footer"><div><div class="price">${money(p.price)}</div><div class="old-price">${money(p.old)}</div></div><button class="add-btn" onclick="addToCart(${p.id})">Add</button></div></article>`).join('')||'<div class="empty">No products found.</div>';}
function setCategory(cat){selected=cat;renderCategories();renderProducts();document.getElementById('products')?.scrollIntoView({behavior:'smooth'});}
function setSort(value,el){sort=value;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));el?.classList.add('active');renderProducts();}
function applySearch(){const input=document.getElementById('searchInput');query=(input?.value||'').trim().toLowerCase();renderProducts();document.getElementById('products')?.scrollIntoView({behavior:'smooth'});}
function renderProductPage(){const root=document.getElementById('productDetail');if(!root)return;const id=Number(new URLSearchParams(location.search).get('id')||1);const p=products.find(x=>x.id===id)||products[0];document.title=`${p.name} — YOOOP`;root.innerHTML=`<div class="detail-grid"><div class="detail-image"><img src="${p.img}" alt="${p.name}"></div><div class="detail-info"><span class="tag">${p.tag}</span><h1>${p.name}</h1><div class="rating">★★★★★ <span class="subtle">${p.rating} · 238 reviews</span></div><div class="detail-price">${money(p.price)} <span>${money(p.old)}</span></div><p>${p.desc}</p><ul class="feature-list"><li>30-day returns</li><li>Secure checkout</li><li>Tracked delivery</li></ul><div class="detail-actions"><button class="primary wide" onclick="addToCart(${p.id})">Add to cart</button><button class="ghost-dark wide" onclick="addToCart(${p.id},true)">Buy now</button></div></div></div>`;}
function renderCartPage(){const root=document.getElementById('cartPage');if(!root)return;const items=cartItems();if(!items.length){root.innerHTML='<div class="empty-card"><h2>Your cart is empty</h2><p>Add something you like and it will appear here.</p><a class="primary-link" href="index.html">Continue shopping</a></div>';return;}const subtotal=items.reduce((a,x)=>a+x.p.price*x.qty,0),shipping=subtotal>=35?0:5.99,total=subtotal+shipping;root.innerHTML=`<div class="cart-layout"><section class="cart-list"><h1>Shopping cart</h1>${items.map(({p,qty})=>`<div class="cart-row"><a href="product.html?id=${p.id}"><img src="${p.img}" alt="${p.name}"></a><div><a class="item-name" href="product.html?id=${p.id}">${p.name}</a><div class="subtle">In stock · Ships with tracking</div><div class="qty-control"><button onclick="changeQty(${p.id},-1)">−</button><span>${qty}</span><button onclick="changeQty(${p.id},1)">+</button><button class="remove" onclick="removeFromCart(${p.id})">Remove</button></div></div><strong>${money(p.price*qty)}</strong></div>`).join('')}</section><aside class="order-summary"><h2>Order summary</h2><div><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div><span>Shipping</span><strong>${shipping?money(shipping):'FREE'}</strong></div><div class="summary-total"><span>Total</span><strong>${money(total)}</strong></div><a class="checkout-link" href="checkout.html">Proceed to checkout</a></aside></div>`;}
function renderCheckout(){const root=document.getElementById('checkoutPage');if(!root)return;const items=cartItems();const subtotal=items.reduce((a,x)=>a+x.p.price*x.qty,0),shipping=subtotal>=35?0:5.99,total=subtotal+shipping;if(!items.length){root.innerHTML='<div class="empty-card"><h2>Your cart is empty</h2><a class="primary-link" href="index.html">Shop now</a></div>';return;}root.innerHTML=`<div class="checkout-layout"><form class="checkout-form" onsubmit="placeOrder(event)"><h1>Checkout</h1><h3>Contact</h3><input required name="email" type="email" placeholder="Email address"><h3>Delivery address</h3><div class="form-grid"><input required name="first" placeholder="First name"><input required name="last" placeholder="Last name"><input required name="address" class="full" placeholder="Street address"><input required name="city" placeholder="City"><input required name="state" placeholder="State"><input required name="zip" placeholder="ZIP code"></div><h3>Payment</h3><div class="payment-note">Demo checkout: no real card is charged yet. Stripe will be connected later.</div><input required placeholder="Card number" value="4242 4242 4242 4242"><div class="form-grid"><input required placeholder="MM/YY" value="12/30"><input required placeholder="CVC" value="123"></div><button class="primary wide" type="submit">Place demo order · ${money(total)}</button></form><aside class="order-summary"><h2>Your order</h2>${items.map(({p,qty})=>`<div class="mini-item"><img src="${p.img}"><span>${p.name} × ${qty}</span><strong>${money(p.price*qty)}</strong></div>`).join('')}<div><span>Shipping</span><strong>${shipping?money(shipping):'FREE'}</strong></div><div class="summary-total"><span>Total</span><strong>${money(total)}</strong></div></aside></div>`;}
function placeOrder(e){e.preventDefault();const items=cartItems();const order={id:'Y'+Date.now().toString().slice(-8),date:new Date().toLocaleDateString(),status:'Processing',items,total:items.reduce((a,x)=>a+x.p.price*x.qty,0)};const orders=JSON.parse(localStorage.getItem('yooop-orders')||'[]');orders.unshift(order);localStorage.setItem('yooop-orders',JSON.stringify(orders));localStorage.removeItem('yooop-cart');cart={};location.href=`orders.html?placed=${order.id}`;}
function renderOrders(){const root=document.getElementById('ordersPage');if(!root)return;const orders=JSON.parse(localStorage.getItem('yooop-orders')||'[]');const placed=new URLSearchParams(location.search).get('placed');root.innerHTML=`${placed?`<div class="success-banner">Order ${placed} was placed successfully.</div>`:''}<h1>Your orders</h1>${orders.length?orders.map(o=>`<article class="order-card"><div class="order-head"><div><strong>Order ${o.id}</strong><div class="subtle">Placed ${o.date}</div></div><span class="status">${o.status}</span></div>${o.items.map(({p,qty})=>`<div class="mini-item"><img src="${p.img}"><span>${p.name} × ${qty}</span><strong>${money(p.price*qty)}</strong></div>`).join('')}<div class="order-total">Total: ${money(o.total)}</div></article>`).join(''):'<div class="empty-card"><h2>No orders yet</h2><a class="primary-link" href="index.html">Start shopping</a></div>'}`;}
function saveProfile(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));localStorage.setItem('yooop-profile',JSON.stringify(data));document.getElementById('profileSaved').textContent='Saved';setTimeout(()=>document.getElementById('profileSaved').textContent='',1500);}
function renderAccount(){const form=document.getElementById('accountForm');if(!form)return;const p=JSON.parse(localStorage.getItem('yooop-profile')||'{}');Object.entries(p).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v});}
function init(){updateCartBadges();renderCategories();renderProducts();renderProductPage();renderCartPage();renderCheckout();renderOrders();renderAccount();document.getElementById('searchInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')applySearch()});}
document.addEventListener('DOMContentLoaded',init);