const products=[
{id:1,name:'Compact Wireless Label Printer',cat:'Electronics',price:24.99,old:34.99,rating:4.8,img:'https://images.unsplash.com/photo-1586769852044-692d6e3703f0?auto=format&fit=crop&w=900&q=80',tag:'Top pick'},
{id:2,name:'Reusable Silicone Food Storage Set',cat:'Home',price:12.49,old:18.99,rating:4.7,img:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=80',tag:'Best value'},
{id:3,name:'Pet Grooming Deshedding Tool',cat:'Pets',price:9.98,old:15.99,rating:4.9,img:'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80',tag:'Loved'},
{id:4,name:'Magnetic Phone Car Mount',cat:'Auto',price:8.99,old:13.49,rating:4.6,img:'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=80',tag:'Fast ship'},
{id:5,name:'USB-C Multiport Travel Hub',cat:'Electronics',price:19.95,old:29.95,rating:4.8,img:'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80',tag:'Trending'},
{id:6,name:'Microfiber Cleaning Cloths 24-Pack',cat:'Home',price:11.99,old:16.99,rating:4.7,img:'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=900&q=80',tag:'Everyday'},
{id:7,name:'Comfort Memory Foam Insoles',cat:'Health',price:14.75,old:21.99,rating:4.5,img:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',tag:'Popular'},
{id:8,name:'Compact Digital Kitchen Scale',cat:'Kitchen',price:10.49,old:14.99,rating:4.8,img:'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80',tag:'Top rated'},
{id:9,name:'Portable Mini Desk Fan',cat:'Local US',price:16.99,old:22.99,rating:4.6,img:'https://images.unsplash.com/photo-1598300056393-4aac492f4344?auto=format&fit=crop&w=900&q=80',tag:'Local US'},
{id:10,name:'Adjustable Laptop Stand',cat:'Electronics',price:21.49,old:31.99,rating:4.9,img:'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=900&q=80',tag:'Best seller'},
{id:11,name:'Heavy-Duty Closet Organizer',cat:'Home',price:17.95,old:25.99,rating:4.5,img:'https://images.unsplash.com/photo-1616486338815-3e9c88d8d98f?auto=format&fit=crop&w=900&q=80',tag:'Smart find'},
{id:12,name:'Rechargeable Book Light',cat:'Local US',price:7.99,old:12.99,rating:4.7,img:'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=900&q=80',tag:'Under $10'}
];
const categories=[['All','✨'],['Electronics','🎧'],['Home','🏠'],['Kitchen','🍳'],['Pets','🐾'],['Local US','🇺🇸']];
let selected='All',sort='featured',query='',cart=JSON.parse(localStorage.getItem('yooop-cart')||'{}');
function money(n){return '$'+n.toFixed(2)}
function renderCategories(){document.getElementById('categories').innerHTML=categories.map(([name,icon])=>`<button class="category ${selected===name?'active':''}" onclick="setCategory('${name}')"><span>${icon}</span><strong>${name}</strong></button>`).join('')}
function getProducts(){let list=products.filter(p=>(selected==='All'||p.cat===selected)&&(!query||p.name.toLowerCase().includes(query)||p.cat.toLowerCase().includes(query)));if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);return list}
function renderProducts(){const list=getProducts();document.getElementById('resultsText').textContent=`${list.length} products`;document.getElementById('productGrid').innerHTML=list.map(p=>`<article class="product"><div class="product-image"><img src="${p.img}" alt="${p.name}"></div><div class="product-info"><span class="tag">${p.tag}</span><div class="product-title">${p.name}</div><div class="rating">★★★★★ <span class="subtle">${p.rating}</span></div><div class="price-row"><div><div class="price">${money(p.price)}</div><div class="old-price">${money(p.old)}</div></div><button class="add-btn" onclick="addToCart(${p.id})">Add</button></div></div></article>`).join('')||'<div class="empty">No products found.</div>'}
function setCategory(cat){selected=cat;renderCategories();renderProducts();document.getElementById('products').scrollIntoView({behavior:'smooth'})}
function setSort(value,el){sort=value;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));el.classList.add('active');renderProducts()}
function applySearch(){query=document.getElementById('searchInput').value.trim().toLowerCase();renderProducts();document.getElementById('products').scrollIntoView({behavior:'smooth'})}
function addToCart(id){cart[id]=(cart[id]||0)+1;saveCart();showToast()}
function changeQty(id,delta){cart[id]=(cart[id]||0)+delta;if(cart[id]<=0)delete cart[id];saveCart()}
function saveCart(){localStorage.setItem('yooop-cart',JSON.stringify(cart));renderCart()}
function renderCart(){const items=Object.entries(cart).map(([id,qty])=>({p:products.find(x=>x.id===Number(id)),qty})).filter(x=>x.p);const count=items.reduce((a,x)=>a+x.qty,0);document.getElementById('cartCount').textContent=count;const el=document.getElementById('cartItems');if(!items.length){el.innerHTML='<div class="empty">Your cart is empty.</div>';document.getElementById('cartSummary').innerHTML='';return}el.innerHTML=items.map(({p,qty})=>`<div class="cart-item"><img src="${p.img}" alt="${p.name}"><div><strong>${p.name}</strong><div class="subtle">${money(p.price)}</div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><span>${qty}</span><button onclick="changeQty(${p.id},1)">+</button></div></div><strong>${money(p.price*qty)}</strong></div>`).join('');const subtotal=items.reduce((a,x)=>a+x.p.price*x.qty,0),shipping=subtotal>=35?0:5.99;document.getElementById('cartSummary').innerHTML=`<div class="price-row"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="price-row"><span>Shipping</span><strong>${shipping?money(shipping):'FREE'}</strong></div><div class="price-row"><span>Total</span><strong>${money(subtotal+shipping)}</strong></div><button class="checkout" onclick="alert('Checkout connection comes next')">Continue to checkout</button>`}
function toggleCart(open){document.getElementById('drawer').classList.toggle('open',open)}
function showToast(){const t=document.getElementById('toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1200)}
document.getElementById('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')applySearch()});
renderCategories();renderProducts();renderCart();