const Y={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const user=Y.get('yooop-user',null);
function updateSession(){document.querySelectorAll('[data-user-name]').forEach(x=>x.textContent=user?.first||'Account');document.querySelectorAll('[data-login-link]').forEach(x=>{x.textContent=user?'Sign out':'Sign in';x.href=user?'#':'login.html';if(user)x.onclick=e=>{e.preventDefault();localStorage.removeItem('yooop-user');location.href='login.html'}})}
function login(e){e.preventDefault();const f=new FormData(e.target);const email=f.get('email');const name=(f.get('name')||email.split('@')[0]||'Customer').trim();Y.set('yooop-user',{first:name.split(' ')[0],name,email});location.href='account.html'}
function register(e){e.preventDefault();const f=new FormData(e.target);Y.set('yooop-user',{first:f.get('first'),name:`${f.get('first')} ${f.get('last')}`.trim(),email:f.get('email')});location.href='account.html'}
function sendMessage(e){e.preventDefault();const box=document.getElementById('messageText');if(!box.value.trim())return;const msgs=Y.get('yooop-messages',[]);msgs.push({from:'You',text:box.value.trim(),time:'Just now'});Y.set('yooop-messages',msgs);box.value='';renderMessages()}
function renderMessages(){const el=document.getElementById('thread');if(!el)return;const msgs=[{from:'YOOOP Support',text:'Hi! How can we help with your order today?',time:'Today, 10:12 AM'},...Y.get('yooop-messages',[])];el.innerHTML=msgs.map(m=>`<div class="bubble ${m.from==='You'?'mine':''}"><strong>${m.from}</strong><p>${m.text}</p><small>${m.time}</small></div>`).join('')}
function createTicket(e){e.preventDefault();const f=new FormData(e.target);const tickets=Y.get('yooop-tickets',[]);tickets.unshift({id:'YT-'+Math.floor(100000+Math.random()*900000),topic:f.get('topic'),status:'Open',created:new Date().toLocaleDateString()});Y.set('yooop-tickets',tickets);document.getElementById('ticketResult').innerHTML=`<div class="success-card">Request submitted. Ticket <strong>${tickets[0].id}</strong> is now open.</div>`;e.target.reset()}
function renderTracking(){const el=document.getElementById('trackingPanel');if(!el)return;const q=new URLSearchParams(location.search);const id=q.get('order')||'YOOOP-10428';el.innerHTML=`<div class="tracking-card"><div class="tracking-head"><div><span class="status-chip">In transit</span><h1>Order ${id}</h1><p class="subtle">Estimated delivery: <strong>Tuesday, July 14</strong></p></div><a class="secondary-btn" href="orders.html">All orders</a></div><div class="track-line"><div class="track-step done"><b>1</b><span>Ordered<small>July 9</small></span></div><div class="track-step done"><b>2</b><span>Shipped<small>July 10</small></span></div><div class="track-step active"><b>3</b><span>In transit<small>Arrived at regional facility</small></span></div><div class="track-step"><b>4</b><span>Delivered<small>Expected July 14</small></span></div></div><div class="shipment-box"><strong>Latest update</strong><p>Package arrived at the carrier facility in Newark, NJ.</p><small>Today at 7:42 AM</small></div></div>`}
function renderEnterpriseOrders(){const el=document.getElementById('enterpriseOrders');if(!el)return;const orders=Y.get('yooop-orders',[]);const demo=[{id:'YOOOP-10428',date:'July 9, 2026',status:'In transit',total:'$42.47',items:'2 items'},{id:'YOOOP-10391',date:'June 28, 2026',status:'Delivered',total:'$19.95',items:'1 item'}];el.innerHTML=[...orders.map(o=>({id:o.id||'YOOOP-'+Date.now().toString().slice(-5),date:o.date||'Recent',status:'Processing',total:o.total||'$0.00',items:`${o.items?.length||1} item(s)`})),...demo].map(o=>`<article class="order-card"><div><span class="status-chip ${o.status==='Delivered'?'delivered':''}">${o.status}</span><h3>${o.id}</h3><p class="subtle">Placed ${o.date} · ${o.items}</p></div><div class="order-actions"><strong>${o.total}</strong><a href="tracking.html?order=${encodeURIComponent(o.id)}">Track package</a><a href="messages.html">Get help</a></div></article>`).join('')}
updateSession();renderMessages();renderTracking();renderEnterpriseOrders();